#!/usr/bin/env bash
# configure web-02 to be identical to web-01, add a custom Nginx response header
sudo apt-get -y update
sudo apt-get -y install nginx
NEW_STRING="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "37i $NEW_STRING" /etc/nginx/sites-available/default
sudo service nginx restart
