#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y

sudo sed -i "s|ENABLED=0|ENABLED=1|g" /etc/default/haproxy

FRONT_END="\\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n"

BACK_END="backend http_back\n\tbalance roundrobin\n\tserver 314-web-01 35.231.59.48:80 check\n\tserver 314-web-02 35.237.55.203:80 check\n"
sudo sed -i "\$a$FRONT_END\n$BACK_END" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
