#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and I hate the kill command when receiving a SIGTERM signal and Y U no love me?! when receiving a SIGINT signal, creates the file /var/run/holbertonscript.pid containing its PID, deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
