#!/usr/bin/env bash
# This script writes I am alive! to the file /tmp/my_process indefinitely, In between every I am alive! message, the program should pause for 2 seconds
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
