#!/usr/bin/env bash
# This script displays numbers from 1 to 100: displays FizzBuzz when number is multiple of 3 and 5, displays Fizz when the number is multiple of 3, displays Buzz when the number is a multiple of 5, otherwise, displays the number
i=1
while [ $i -le 100 ]
do
	if [ $(( i % 15 )) -eq 0 ]
	then
	    echo "FizzBuzz"
	elif [ $(( i % 3 )) -eq 0 ]
	then
	    echo "Fizz"
	elif [ $(( i % 5 )) -eq 0 ]
	then
	    echo "Buzz"
	else
	    echo $i
	fi
	i=$(( i + 1 ))
done
