#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    i=$(( i + 1 ))
done
