#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01
sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw disable
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
