#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get -y install nginx
echo "Holberton School for the win!" | tee /usr/share/nginx/html/index.html > /dev/null
service nginx restart

sed -i "s|location / {|location /redirect_me {|g"  /etc/nginx/sites-available/default
sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g" /etc/nginx/sites-available/default
service nginx restart
