#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get -y install nginx
echo "Holberton School for the win!" | tee /usr/share/nginx/html/index.html > /dev/null
service nginx restart

sed -i "s|location / {|location /redirect_me {|g"  /etc/nginx/sites-available/default
sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g" /etc/nginx/sites-available/default
service nginx restart

NEW_STRING="\\\t#location = /404.html {\n\t#\troot /usr/share/nginx/html;\n\t#}\n"

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html > /dev/null
sed -i "44i $NEW_STRING" /etc/nginx/sites-available/default
service nginx restart
