#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" | tee /usr/share/nginx/html/index.html > /dev/null
service nginx restart

sed -i "s|location / {|location /redirect_me {|g"  /etc/nginx/sites-available/default
sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g" /etc/nginx/sites-available/default
service nginx restart

NEW_STRING="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null
sudo sed -i "37i $NEW_STRING" /etc/nginx/sites-available/default
sudo service nginx restart
