#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/'127.0.0.2 localhost'/g ~/hosts.new
sed -i '/127.0.0.2 localhost/a 8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
