#!/usr/bin/env bash
# configures the container where nginx must be running as nginx user and nginx must be listening on all active IPs on port 8080
sudo apt-get update -y
sudo apt-get install nginx -y
sed -i "s|user www-data| user nginx|g" /etc/nginx/nginx.conf
sed -i "s|listen 80 | listen 8080 |g" /etc/nginx/sites-available/default
sed -i "s|80 default_server ipv6only=on|8080 default_server ipv6only=on|g" /etc/nginx/sites-available/default
sudo service nginx restart
