#!/usr/bin/env bash
# configures the container where nginx must be running as nginx user and nginx must be listening on all active IPs on port 8080
sudo pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i "s|80|8080|g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
